	import UserController from './UserController.js';
	import SimController from './SimController.js';
	import PrestamoController from './PrestamoController.js';
	export default (app) => {
		const userController = new UserController();
		const simController = new SimController();
		const prestamoControlle = new PrestamoController();
		app.get('/users', userController.getAll);
		app.post('/users', userController.create);
		app.get('/users/:userId', userController.get);
		app.put('/users/:userId', userController.update);
		app.delete('/users/:userId', userController.delete);
		app.post('/login', userController.login);
		app.get('/sims', simController.getAllSims);
		app.delete('/sims/:simId', simController.deleteSims);
		app.post('/CreateSims', simController.createSims);
		app.post('/createPrestamos', prestamoControlle.createPrestamos);
		app.get('/mostrarPrestamos', prestamoControlle.mostrarPrestamos);
		app.delete('/mostrarPrestamos/:prestId', prestamoControlle.deletePrestamos);
	};